[workspace]
resolver = "2"
members = ["netscout-core", "netscout-cli", "netscout-tui"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/redbasecap-buiss/netscout"
authors = ["Nicola Spieser <redbasecap-buiss@users.noreply.github.com>"]
